version: '3'
services:
  pen-server:
    build: .
    image: segware/pentaho_server:8.2
    container_name: pentaho-server
    restart: always
    ports:
      - "8081:8080"
    volumes:
      - ./logs:/opt/pentaho/pentaho-server/tomcat/logs
    environment:
      - COMPOSE_CONVERT_WINDOWS_PATHS=1 #windows only
      - TZ=America/Sao_Paulo

